### ISSUE TITLE
Crash on Android 7.1

### ISSUE THREAD

**Issue by congtaowang** [weizongwei5/AndroidScreenShot_SysApi#1]
FATAL EXCEPTION: main
                                                                            Process: xxxxxxxxxxxxxxxxxx, PID: 31490
                                                                            java.lang.UnsupportedOperationException: The producer output buffer format 0x1 doesn't match the ImageReader's configured buffer format 0x4.
                                                                                at android.media.ImageReader.nativeImageSetup(Native Method)
                                                                                at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:340)
                                                                                at android.media.ImageReader.acquireNextImage(ImageReader.java:394)
                                                                                at android.media.ImageReader.acquireLatestImage(ImageReader.java:287)
                                                                                at xxxxxxxxxxxxxxxxxx.Snapshot$Shotter$1.run(Snapshot.java:313)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

**Comment by BruceWind** [comment]
It's Huawei?

**Comment by BruceWind** [comment]
我这边无法复现。应该是设备不支持PixelFormat.RGB_565，请尝试选择RGBA_8888。 再不行就看这个文档改。https://developer.android.com/reference/android/graphics/PixelFormat.html

**Comment by BruceWind** [comment]
已修复：[009ae1e952475b69bb8c34c4f2b39e6dfe656c70](https://github.com/weizongwei5/AndroidScreenShot_SysApi/commit/009ae1e952475b69bb8c34c4f2b39e6dfe656c70)
