### ISSUE TITLE
crash on 6.0 redmi 4A

### ISSUE THREAD

**Issue by wengjiajun214000** [weizongwei5/AndroidScreenShot_SysApi#2]
java.lang.UnsupportedOperationException: The producer output buffer format 0x1 doesn't match the ImageReader's configured buffer format 0x4.
                                                                                              at android.media.ImageReader.nativeImageSetup(Native Method)
                                                                                              at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:327)
                                                                                              at android.media.ImageReader.acquireNextImage(ImageReader.java:375)
                                                                                              at android.media.ImageReader.acquireLatestImage(ImageReader.java:277)
                                                                                              at com.androidyuan.androidscreenshot_sysapi.Shotter$1.run(Shotter.java:97)
                                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5437)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by BruceWind** [comment]
我这边无法复现。我翻阅了很多的类似的截屏开源的项目都有人反馈同样的崩溃，这个不一定会无解的。应该是设备不支持PixelFormat.RGB_565，请尝试选择RGBA_8888。 再不行就看这个文档改。https://developer.android.com/reference/android/graphics/PixelFormat.html


或者，推荐你参考：https://github.com/googlesamples/android-ScreenCapture
这是个google的录屏demo，不是截屏。但是使用的 API是一样的。

**Comment by BruceWind** [comment]
已修复：[009ae1e952475b69bb8c34c4f2b39e6dfe656c70](https://github.com/weizongwei5/AndroidScreenShot_SysApi/commit/009ae1e952475b69bb8c34c4f2b39e6dfe656c70)
